// <auto-generated />
namespace EstacionamentoFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriaBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriaBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201907040848243_CriaBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
