// <auto-generated />
namespace EstacionamentoFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class validacoes_Veiculo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validacoes_Veiculo));
        
        string IMigrationMetadata.Id
        {
            get { return "201906171011591_validacoes_Veiculo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
